version: '3.9'

services:
  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  auth:
    image: "oven/bun"
    entrypoint: []
    command: "/bin/sh -c 'bun install && bun run --watch src/index.ts'"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.127.0.0.1.nip.io`)"
      - "traefik.http.services.auth.loadbalancer.server.port=3000"
    volumes:
      - "./api/auth:/home/bun/app"

  kculture-api:
    image: "oven/bun"
    entrypoint: []
    command: "/bin/sh -c 'bun install && bun run --watch src/index.ts'"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kculture-socketio.rule=Host(`kculture.api.127.0.0.1.nip.io`) && PathPrefix(`/socket.io`)"
      - "traefik.http.routers.kculture-socketio.service=kculture-socketio"
      - "traefik.http.services.kculture-socketio.loadbalancer.server.port=3001"
      - "traefik.http.routers.kculture-rest.rule=Host(`kculture.api.127.0.0.1.nip.io`) && !PathPrefix(`/socket.io`)"
      - "traefik.http.routers.kculture-rest.service=kculture-rest"
      - "traefik.http.services.kculture-rest.loadbalancer.server.port=3000"
    volumes:
      - "./api/kculture:/home/bun/app"
    depends_on:
      - kculture-db

  kculture-front:
    image: "oven/bun"
    entrypoint: []
    command: "/bin/sh -c 'bun install && bunx --bun vite'"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kculture.rule=Host(`kculture.127.0.0.1.nip.io`)"
      - "traefik.http.routers.kculture.service=kculture"
      - "traefik.http.services.kculture.loadbalancer.server.port=5173"
    volumes:
      - "./frontend/kculture:/home/bun/app"
    depends_on:
      - kculture-api

  kculture-db:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    labels:
      - "traefik.enable=false"

networks:
  default:
    name: traefik_default
